# Machine learning Workshop 
This document contains the content of the machine learning Workshop that we're about to do ;p. 

### Table of content 
1. Machine learning 
    1. What's machine learning ? 
    2. What are the steps to create a machine learning algorithm ? 
    3. Machine learning Terminology
2. Deep learning  
    1. The Human Nervous System
    2. Perceptrons
    3. Neural Network OR MultiLayer Perceptron
    4. FeedForward 
    5. Backpropagation 
3. Implementing Neural Network with Scikit-Learn
    1. Datasets 
    2. Help me find the steps to create our classifier 
    3. Evaluating the algorithm 

![](Images/start.JPG)
    


# Machine learning 
## What's Machine learning ? 
Humans have an ability to identify patterns within the accessible information with an astonishingly high degree of accuracy. Whenever you see a car or a bicycle you can immediately recognize what they are. This is because we have learned over a period of time how a car and bicycle looks like and what their distinguishing features are. But how can we give those abilities to a computer ? 

![](Images/ml.gif)

## What are the steps to create an ML APP ? 
![](Images/steps.JPG)

## Machine learning Terminology 
### Some examples of machine learning 
![](Images/fb.JPG)


### Let's see what you already know 

#### HeartSound 
A machine learning algorithm uses heart sound from different patient to find differences and classify them. 

#### Pedestrian on the road 
An AI that is learning to identify pedestrians on a street is trained with 2 million short videos of street scenes from self-driving cars. Some of the videos contain no pedestrians at all while others have up to 25. A variety of learning algorithms are trained on the data with each having access to the correct answers. Each algorithm develops a variety of models to identify pedestrians in fast moving scenes. The algorithms are then tested against another set of data to evaluate accuracy and precision.

#### Let's simplify ... Dogs vs Cats ? 

#### Generalization 
> The goal of ML is never to make “perfect” guesses, because ML deals in domains where there is no such thing. The goal is to make guesses that are good enough to be useful.


# Deep learning 
## The human nervous system 
Human nervous system consists of billions of neurons. These neurons collectively process input received from sensory organs, process the information, and decides what to do in reaction to the input. A typical neuron in the human nervous system has three main parts: dendrites, nucleus, and axons. The information passed to a neuron is received by dendrites. The nucleus is responsible for processing this information. The output of a neuron is passed to other neurons via the axon, which is connected to the dendrites of other neurons further down the network.

![](Images/dendrides.png) 

`What the frog’s eye tells the frog’s brain`
## Perceptron 
Artificial neural networks are inspired by the human neural network architecture. The simplest neural network consists of only one neuron and is called a perceptron, as shown in the figure below:
![](Images/perceptron.JPG)

A perceptron has one input layer and one neuron. Input layer acts as the dendrites and is responsible for receiving the inputs. The number of nodes in the input layer is equal to the number of features in the input dataset. Each input is multiplied with a weight (which is typically initialized with some random value) and the results are added together. The sum is then passed through an activation function. The activation function of a perceptron resembles the nucleus of human nervous system neuron. It processes the information and yields an output. In the case of a perceptron, this output is the final outcome. However, in the case of multilayer perceptrons, the output from the neurons in the previous layer serves as the input to the neurons of the proceeding layer.

## MultiLayer Perceptron

Now that we know what a single layer perceptron is, we can extend this discussion to multilayer perceptrons, or more commonly known as artificial neural networks. A single layer perceptron can solve simple problems where data is linearly separable in to 'n' dimensions, where 'n' is the number of features in the dataset. However, in case of non-linearly separable data, the accuracy of single layer perceptron decreases significantly. Multilayer perceptrons, on the other hand, can work efficiently with non-linearly separable data.

### In search of non linearity 
#### Feature crosses 

![](Images/LinearProblem2.png)
However if we use a model that is too complicated, such as one with too many crosses, we give it the opportunity to fit to the noise in the training data, often at the cost of making the model perform badly on test data.

#### Neural networks 
Neural networks are a more sophisticated version of feature crosses. In essence, neural networks learn the appropriate feature crosses for you.
![](Images/Deep-learning-ai-machine-matrix2.gif)
A neural network executes in two phases: Feed-Forward and Back Propagation.

##### Activation functions 
###### Sigmoid 
![](Images/sigmoid.jpg)
![](Images/SigmoidFunction.png)
###### Relu 
![](Images/relu.jpg)
![](Images/relu2.jpg)
###### Tanh
![](Images/1200px-Hyperbolic_Tangent.svg.png)

## FeedForward 
Following are the steps performed during the feed-forward phase:

1. The values received in the input layer are multiplied with the weights. A bias is added to the summation of the inputs and weights in order to avoid null values.
2. Each neuron in the first hidden layer receives different values from the input layer depending upon the weights and bias. Neurons have an activation function that operates upon the value received from the input layer. The activation function can be of many types, like a step function, sigmoid function, relu function, or tanh function. As a rule of thumb, relu function is used in the hidden layer neurons and sigmoid function is used for the output layer neuron.
3. The outputs from the first hidden layer neurons are multiplied with the weights of the second hidden layer; the results are summed together and passed to the neurons of the proceeding layers. This process continues until the outer layer is reached. The values calculated at the outer layer are the actual outputs of the algorithm.

The feed-forward phase consists of these three steps. However, the predicted output is not necessarily correct right away; it can be wrong, and we need to correct it. The purpose of a learning algorithm is to make predictions that are as accurate as possible. To improve these predicted results, a neural network will then go through a back propagation phase. During back propagation, the weights of different neurons are updated in a way that the difference between the desired and predicted output is as small as possible.

## BackPropagation 
Back propagation phase consists of the following steps:

1. The error is calculated by quantifying the difference between the predicted output and the desired output. This difference is called "loss" and the function used to calculate the difference is called the "loss function". Loss functions can be of different types e.g. mean squared error or cross entropy functions. Remember, neural networks are supervised learning algorithms that need the desired outputs for a given set of inputs, which is what allows it to learn from the data.
2. Once the error is calculated, the next step is to minimize that error. To do so, partial derivative of the error function is calculated with respect to all the weights and biases. This is called gradient decent. The derivatives can be used to find the slope of the error function. If the slop is positive, the value of the weights can be reduced or if the slop is negative the value of weight can be increased. This reduces the overall error. The function that is used to reduce this error is called the optimization function.

This one cycle of feed-forward and back propagation is called one "epoch". This process continues until a reasonable accuracy is achieved. There is no standard for reasonable accuracy, ideally you'd strive for 100% accuracy, but this is extremely difficult to achieve for any non-trivial dataset. In many cases 90%+ accuracy is considered acceptable, but it really depends on your use-case.

In [2]:
import numpy as np 
import pandas as pd

# Location of dataset
url = "Datasets/Iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Target']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=names) 
print(type(irisdata))
irisdata.head()

<class 'pandas.core.frame.DataFrame'>


sepal-length  sepal-width  petal-length  petal-width       Target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
print("Iris data set dimensions : {}".format(irisdata.shape))

Iris data set dimensions : (150, 5)


In [4]:
print(irisdata.groupby('Target').size())

Target
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64


In [5]:
import seaborn as sns
sns.countplot(irisdata['Target'],label="Count")

In [6]:
irisdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal-length    150 non-null float64
sepal-width     150 non-null float64
petal-length    150 non-null float64
petal-width     150 non-null float64
Target          150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [7]:
irisdata.isnull().sum()
irisdata.isna().sum()

sepal-length    0
sepal-width     0
petal-length    0
petal-width     0
Target          0
dtype: int64

In [8]:
# Assign data from first four columns to X variable
X = irisdata.iloc[:, 0:4]

# Assign data from first fifth columns to y variable
y = irisdata.select_dtypes(include=[object])  
y.head()

Target
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [9]:
a = y.Target.unique()  
print(a[0])

Iris-setosa


In [10]:
from sklearn import preprocessing  
le = preprocessing.LabelEncoder()

y = y.apply(le.fit_transform) 
y.Target.unique()

array([0, 1, 2], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
print(y_train)

     Target
61        1
144       2
63        1
54        1
124       2
39        0
103       2
28        0
97        1
98        1
26        0
82        1
78        1
24        0
148       2
96        1
136       2
116       2
69        1
74        1
142       2
47        0
84        1
107       2
114       2
51        1
143       2
66        1
88        1
108       2
..      ...
89        1
4         0
49        0
29        0
41        0
31        0
1         0
127       2
73        1
95        1
17        0
18        0
11        0
16        0
93        1
19        0
138       2
36        0
112       2
79        1
133       2
90        1
44        0
135       2
68        1
33        0
115       2
87        1
67        1
83        1

[120 rows x 1 columns]


In [12]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test) 

In [13]:
from sklearn.neural_network import MLPClassifier  
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
mlp.fit(X_train, y_train.values.ravel()) 

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [14]:
predictions = mlp.predict(X_test)  

## Scores 
### Classification Accuracy 
Classification Accuracy is great, but gives us the false sense of achieving high accuracy.
![](Images/Accuracy.jpg)
### Logarithmic Loss 
Logarithmic Loss or Log Loss, works by penalising the false classifications. It works well for multi-class classification.
![](Images/log.jpg)
### Confusion Matrix 

|n = 200      | Predicted : YES | Predicted : NO |
|-------------|-----------------|----------------|
|Actual : YES |       50        |       60       |  
|Actual : NO  |       20        |       70       | 

1. True Positives : The cases in which we predicted YES and the actual output was also YES.
2. True Negatives : The cases in which we predicted NO and the actual output was NO.
3. False Positives : The cases in which we predicted YES and the actual output was NO.
4. False Negatives : The cases in which we predicted NO and the actual output was YES.

### F1 Score
![](Images/f1.jpg)
![](Images/precision.jpg)
![](Images/recall.jpg)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  

[[ 6  1  0]
 [ 0 11  0]
 [ 0  0 12]]
             precision    recall  f1-score   support

          0       1.00      0.86      0.92         7
          1       0.92      1.00      0.96        11
          2       1.00      1.00      1.00        12

avg / total       0.97      0.97      0.97        30



# Change the number of the hidden layer 


In [16]:
from sklearn.neural_network import MLPClassifier  
mlp = MLPClassifier(hidden_layer_sizes=(1), max_iter=1000)  
mlp.fit(X_train, y_train.values.ravel()) 
predictions = mlp.predict(X_test)  
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  

[[ 0  7  0]
 [ 0  6  5]
 [ 0  0 12]]
             precision    recall  f1-score   support

          0       0.00      0.00      0.00         7
          1       0.46      0.55      0.50        11
          2       0.71      1.00      0.83        12

avg / total       0.45      0.60      0.51        30



D:\Anaconda\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [18]:
from sklearn.neural_network import MLPClassifier  
mlp = MLPClassifier(hidden_layer_sizes=(4), max_iter=1000)  
mlp.fit(X_train, y_train.values.ravel()) 
predictions = mlp.predict(X_test)  
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions)) 

[[ 7  0  0]
 [ 0 11  0]
 [ 0  0 12]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         7
          1       1.00      1.00      1.00        11
          2       1.00      1.00      1.00        12

avg / total       1.00      1.00      1.00        30



D:\Anaconda\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
